config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  resources :users
  resources :sessions
  delete '/logout' => 'sessions#destroy', as: :logout

  resources :categories, only: [:show]
  resources :products, only: [:show]

  namespace :admin do
    root 'sessions#new'
    resources :sessions
    resources :categories
    resources :products do
      resources :product_images, only: [:index, :create, :destroy, :update]
    end
  end
end

app/models/product.rb
class Product < ApplicationRecord

  validates :category_id, presence: { message: "Category must not be empty" }
  validates :title, presence: { message: "Title mush not be empty" }
  validates :status, inclusion: { in: %w[on off], 
    message: "The status of the product mush be on | off" }
  validates :amount, numericality: { only_integer: true,
    message: "Amount mush be an integet!" },
    if: proc { |product| !product.amount.blank? }
  validates :amount, presence: { message: "Amount must not be empty" }
  validates :msrp, presence: { message: "MSRP mush not be empty" }
  validates :msrp, numericality: { message: "MSRP mush be a number" },
    if: proc { |product| !product.msrp.blank? }
  validates :price, numericality: { message: "Price must be a number" },
    if: proc { |product| !product.price.blank? }
  validates :price, presence: { message: "Price must not be empty" }
  validates :description, presence: { message: "Description must not be empty" }

  belongs_to :category
  has_many :product_images, -> { order(weight: 'desc') }, dependent: :destroy
  has_one :main_product_image, -> {order(weight: 'desc')},
   class_name: :ProductImage

  before_create :set_default_attrs

  scope :onshelf, -> { where(status: Status::On) }
  
  module Status
    On = 'on'
    Off = 'off'
  end

  private
  def set_default_attrs
    self.uuid = RandomCode.generate_product_uuid
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::BaseController

    before_action :find_product, only: [:edit, :update, :destroy]

    def index
        @products = Product.page(params[:page] || 1).per_page(params[:per_page] || 10)
         .order("id desc")
    end


    def new
        @product = Product.new
        @root_categories = Category.roots
    end

    def create
        @product = Product.new(params.require(:product).permit!)
        @root_categories = Category.roots
    
        if @product.save
          flash[:notice] = "Saved Successfully"
          redirect_to admin_products_path
        else
          render action: :new
        end
    end

    def edit
        @root_categories = Category.roots
        render action: :new
    end

    def update
        @product.attributes = params.require(:product).permit!
        @root_categories = Category.roots
        if @product.save
          flash[:notice] = "Update finshed"
          redirect_to admin_products_path
        else
          render action: :new
        end
    end

    def destroy 
        if @product.destroy
        flash[:notice] = "Deletion Successes"
        redirect_to admin_products_path
      else
        flash[:notice] = "Fail to delete"
        redirect_back fallback_location: root_path
      end
    end

    private
    def find_product
      @product = Product.find(params[:id])
    end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

    def show
      fetch_home_data
      
      @product = Product.find(params[:id])
    end
  
  end

app/views/admin/products/index.html.erb
<div>
  <div class="pull-right">
    <%= link_to "Create new product", new_admin_product_path, class: "btn btn-primary" %>
  </div>

  <h1>
    Product(<%= @products.total_entries %>)
  </h1>
</div>

<div>
  <table class="table table-striped">
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>UUID/SKU</th>
      <th>MSRP</th>
      <th>Price</th>
      <th>Amount</th>
      <th>Status</th>
      <th></th>
    </tr>

    <% @products.each do |product| %>
      <tr>
      <td><%= product.id %></td>
      <td><%= product.title %></td>
      <td><%= product.uuid %></td>
      <td><%= product.msrp %></td>
      <td><%= product.price %></td>
      <td><%= product.amount %></td>
      <td><%= product.status %></td>
        <td align="right">
          <%= link_to "Edit", edit_admin_product_path(product) %> 
          <%= link_to "Delete", admin_product_path(product), method: :delete, 'data-confirm': "Are you sure to delete?" %>
          <%= link_to "Image management", admin_product_product_images_path(product_id: product) %>
        </td>
      </tr>
    <% end -%>
  </table>

  <%= will_paginate @products %>
</div>

app/views/admin/products/new.html.erb
<div>
  <h1><%= @product.new_record? ? "Create a new product" : "Modify a product ##{params[:id]}" %></h1>
</div>

<div class="form-body">
  <%= form_for @product, 
    url: (@product.new_record? ? admin_products_path : admin_product_path(@product)), 
    method: (@product.new_record? ? 'post' : 'put'), 
    html: { class: 'form-horizontal' } do |f| %>
    
    <% unless @product.errors.blank? %>
      <div class="alert alert-danger">
        <ul class="list-unstyled">
          <% @product.errors.messages.values.flatten.each do |error| %>
            <li><i class="fa fa-exclamation-circle"></i> <%= error %></li>
          <% end -%>
        </ul>
      </div>
    <% end -%>

<div class="form-group">
   <label for="title" class="col-sm-2 control-label">Name:*</label>
    <div class="col-sm-5">
      <%= f.text_field :title, class: "form-control" %>
    </div>
  </div>
<div class="form-group">
   <label for="category_id" class="col-sm-2 control-label">Category:</label>
    <div class="col-sm-5">
      <select name="product[category_id]">
        <option></option>
        <% @root_categories.each do |category| %>
          <optgroup label="<%= category.title %>"></optgroup>

          <% category.children.each do |sub_category| %>
            <option value="<%= sub_category.id %>" <%= @product.category_id == sub_category.id ? 'selected' : '' %>><%= sub_category.title %></option>
          <% end -%>
        <% end -%>
      </select>
    </div>
  </div>

  <div class="form-group">
  <label for="title" class="col-sm-2 control-label">Status:*</label>
  <div class="col-sm-5">
    <select name="product[status]">
      <% [[Product::Status::On, 'Avaliable'], [Product::Status::Off, 'Not avaliable']].each do |row| %>
        <option value="<%= row.first %>" <%= 'selected' if @product.status == row.first %>><%= row.last %></option>
      <% end -%>
    </select>
  </div>
</div>


<div class="form-group">
  <label for="amount" class="col-sm-2 control-label">Amount*:</label>
    <div class="col-sm-5">
      <%= f.text_field :amount, class: "form-control" %> Must be an integer
    </div>
</div>

<div class="form-group">
<label for="price" class="col-sm-2 control-label">Price*:</label>
<div class="col-sm-5">
  <%= f.text_field :price, class: "form-control" %>
</div>
</div>
<div class="form-group">
<label for="msrp" class="col-sm-2 control-label">MSRP*:</label>
<div class="col-sm-5">
  <%= f.text_field :msrp, class: "form-control" %>
</div>
</div>
<div class="form-group">
<label for="description" class="col-sm-2 control-label">Description*:</label>
<div class="col-sm-5">
  <%= f.text_area :description, class: "form-control" %>
</div>
</div>
<div class="form-group">
<div class="col-sm-offset-2 col-sm-8">
  <%= f.submit (@product.new_record? ? "Create a new product"  : "Modify a product "), class: "btn btn-default" %>
</div>
</div>
<% end -%>
</div>